networks:
  reverse-proxy:
    external: true
  prometheus:
    external: true

secrets:
  CLOUDFLARE_DNS_API_TOKEN:
    file: CLOUDFLARE_DNS_API_TOKEN.secret

services:
  traefik:
    image: traefik:3
    restart: unless-stopped
    secrets:
      - CLOUDFLARE_DNS_API_TOKEN
    environment:
      CLOUDFLARE_DNS_API_TOKEN_FILE: /run/secrets/CLOUDFLARE_DNS_API_TOKEN
    env_file:
      # the traefik_dynamic.yaml config's templating functionality doesn't have support for reading secrets from files
      # https://doc.traefik.io/traefik/reference/routing-configuration/other-providers/file/#go-templating
      # furthermore, the plugin oauth plugin configuration doesn't support it either
      # so we set the necessary secrets as environment variables via env files
      - OIDC_CLIENT_SECRET_TOKEN.secret
      - OIDC_ENCRYPTION_SECRET.secret
    ports:
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik_dynamic.yaml:/etc/traefik/traefik_dynamic.yaml:ro
      - ./certs:/etc/certs
    networks:
      - reverse-proxy
      - prometheus
    labels:
      - wud.watch.digest=true
      - wud.tag.exclude=^.*$
      - wud.link.template=https://github.com/traefik/traefik/releases
